### ISSUE TITLE
Error: Cannot find module './convert-source-map'

### ISSUE THREAD

**Issue by wellyshen** [halt-hammerzeit/webpack-isomorphic-tools#134]
After I upgraded css-loader from v0.26.2 to v0.27.2, the following error occurs :
<img width="1193" alt="2017-03-13 2 58 50" src="https://cloud.githubusercontent.com/assets/21308003/23844594/2e8ddb4c-07fe-11e7-9a29-448de406b610.png">

**Comment by halt-hammerzeit** [comment]
I'm having this too

**Comment by halt-hammerzeit** [comment]
Fixed in the latest release

**Comment by halt-hammerzeit** [comment]
ooops, not yet published, a test is failing

**Comment by wellyshen** [comment]
OK thanks

**Comment by halt-hammerzeit** [comment]
Released `webpack-isomorphic-tools@3.0.2`

**Comment by wellyshen** [comment]
@halt-hammerzeit Thank you, it works 👍
